[2023-12-02T14:14:22.655+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: compare_task_score.test_model manual__2023-12-02T11:13:02.632939+00:00 [queued]>
[2023-12-02T14:14:22.830+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: compare_task_score.test_model manual__2023-12-02T11:13:02.632939+00:00 [queued]>
[2023-12-02T14:14:22.830+0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-02T14:14:22.871+0300] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): test_model> on 2023-12-02 11:13:02.632939+00:00
[2023-12-02T14:14:22.893+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'compare_task_score', 'test_model', 'manual__2023-12-02T11:13:02.632939+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/run_airflow.py', '--cfg-path', '/tmp/tmpqxnfwcen']
[2023-12-02T14:14:22.897+0300] {standard_task_runner.py:85} INFO - Job 75: Subtask test_model
[2023-12-02T14:14:22.876+0300] {standard_task_runner.py:57} INFO - Started process 16715 to run task
[2023-12-02T14:14:23.216+0300] {task_command.py:416} INFO - Running <TaskInstance: compare_task_score.test_model manual__2023-12-02T11:13:02.632939+00:00 [running]> on host MLOPS-3-3.myguest.virtualbox.org
[2023-12-02T14:14:23.677+0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='compare_task_score' AIRFLOW_CTX_TASK_ID='test_model' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T11:13:02.632939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-02T11:13:02.632939+00:00'
[2023-12-02T14:14:23.680+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-02T14:14:23.696+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/petr/project/scripts/test_model.py']
[2023-12-02T14:14:23.724+0300] {subprocess.py:86} INFO - Output:
[2023-12-02T14:14:27.463+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-02T14:14:27.475+0300] {subprocess.py:93} INFO -   File "/home/petr/project/scripts/test_model.py", line 34, in <module>
[2023-12-02T14:14:27.476+0300] {subprocess.py:93} INFO -     test_score.append(model_2.score(X_test, y_test))
[2023-12-02T14:14:27.476+0300] {subprocess.py:93} INFO -   File "/home/petr/project/venv/lib/python3.10/site-packages/sklearn/base.py", line 668, in score
[2023-12-02T14:14:27.480+0300] {subprocess.py:93} INFO -     return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
[2023-12-02T14:14:27.480+0300] {subprocess.py:93} INFO -   File "/home/petr/project/venv/lib/python3.10/site-packages/sktime/classification/interval_based/_tsf.py", line 131, in predict
[2023-12-02T14:14:27.482+0300] {subprocess.py:93} INFO -     return BaseClassifier.predict(self, X=X, **kwargs)
[2023-12-02T14:14:27.482+0300] {subprocess.py:93} INFO -   File "/home/petr/project/venv/lib/python3.10/site-packages/sktime/classification/base.py", line 230, in predict
[2023-12-02T14:14:27.483+0300] {subprocess.py:93} INFO -     self.check_is_fitted()
[2023-12-02T14:14:27.483+0300] {subprocess.py:93} INFO -   File "/home/petr/project/venv/lib/python3.10/site-packages/sktime/base/_base.py", line 483, in check_is_fitted
[2023-12-02T14:14:27.496+0300] {subprocess.py:93} INFO -     raise NotFittedError(
[2023-12-02T14:14:27.496+0300] {subprocess.py:93} INFO - sktime.exceptions.NotFittedError: This instance of TimeSeriesForestClassifier has not been fitted yet; please call `fit` first.
[2023-12-02T14:14:28.519+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-02T14:14:28.575+0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/petr/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-02T14:14:28.626+0300] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=compare_task_score, task_id=test_model, execution_date=20231202T111302, start_date=20231202T111422, end_date=20231202T111428
[2023-12-02T14:14:28.710+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 75 for task test_model (Bash command failed. The command returned a non-zero exit code 1.; 16715)
[2023-12-02T14:14:28.781+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-02T14:14:28.860+0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
