[2023-11-08T20:06:35.441+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_task_score.get_data manual__2023-11-08T17:06:19.522632+00:00 [queued]>
[2023-11-08T20:06:35.591+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_task_score.get_data manual__2023-11-08T17:06:19.522632+00:00 [queued]>
[2023-11-08T20:06:35.592+0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-08T20:06:36.290+0300] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-11-08 17:06:19.522632+00:00
[2023-11-08T20:06:36.296+0300] {standard_task_runner.py:57} INFO - Started process 40558 to run task
[2023-11-08T20:06:36.431+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'my_task_score', 'get_data', 'manual__2023-11-08T17:06:19.522632+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/run_airflow.py', '--cfg-path', '/tmp/tmpw5fqh3sv']
[2023-11-08T20:06:36.433+0300] {standard_task_runner.py:85} INFO - Job 28: Subtask get_data
[2023-11-08T20:06:37.219+0300] {task_command.py:416} INFO - Running <TaskInstance: my_task_score.get_data manual__2023-11-08T17:06:19.522632+00:00 [running]> on host MLOPS-3-3.myguest.virtualbox.org
[2023-11-08T20:06:37.855+0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='my_task_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T17:06:19.522632+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T17:06:19.522632+00:00'
[2023-11-08T20:06:37.857+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T20:06:37.874+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/petr/project/scripts/get_data.py']
[2023-11-08T20:06:37.927+0300] {subprocess.py:86} INFO - Output:
[2023-11-08T20:06:39.839+0300] {subprocess.py:93} INFO - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
[2023-11-08T20:06:39.839+0300] {subprocess.py:93} INFO - Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
[2023-11-08T20:06:39.839+0300] {subprocess.py:93} INFO - To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
[2023-11-08T20:06:41.880+0300] {subprocess.py:93} INFO - Collecting PyGithub
[2023-11-08T20:06:41.883+0300] {subprocess.py:93} INFO -   Using cached PyGithub-2.1.1-py3-none-any.whl (302 kB)
[2023-11-08T20:06:41.922+0300] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (2.8.2)
[2023-11-08T20:06:41.935+0300] {subprocess.py:93} INFO - Requirement already satisfied: pyjwt[crypto]>=2.4.0 in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (2.8.0)
[2023-11-08T20:06:41.935+0300] {subprocess.py:93} INFO - Requirement already satisfied: urllib3>=1.26.0 in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (2.0.7)
[2023-11-08T20:06:41.936+0300] {subprocess.py:93} INFO - Requirement already satisfied: requests>=2.14.0 in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (2.31.0)
[2023-11-08T20:06:41.936+0300] {subprocess.py:93} INFO - Requirement already satisfied: Deprecated in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (1.2.14)
[2023-11-08T20:06:41.936+0300] {subprocess.py:93} INFO - Requirement already satisfied: typing-extensions>=4.0.0 in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (4.8.0)
[2023-11-08T20:06:42.190+0300] {subprocess.py:93} INFO - Collecting pynacl>=1.4.0
[2023-11-08T20:06:42.782+0300] {subprocess.py:93} INFO -   Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
[2023-11-08T20:06:44.217+0300] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 856.7/856.7 KB 602.1 kB/s eta 0:00:00
[2023-11-08T20:06:44.333+0300] {subprocess.py:93} INFO - Requirement already satisfied: cryptography>=3.4.0 in /home/petr/project/venv/lib/python3.10/site-packages (from pyjwt[crypto]>=2.4.0->PyGithub) (41.0.5)
[2023-11-08T20:06:44.372+0300] {subprocess.py:93} INFO - Requirement already satisfied: cffi>=1.4.1 in /home/petr/project/venv/lib/python3.10/site-packages (from pynacl>=1.4.0->PyGithub) (1.16.0)
[2023-11-08T20:06:44.437+0300] {subprocess.py:93} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/petr/project/venv/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub) (2023.7.22)
[2023-11-08T20:06:44.438+0300] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/petr/project/venv/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub) (3.4)
[2023-11-08T20:06:44.438+0300] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/petr/project/venv/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub) (2.1.1)
[2023-11-08T20:06:44.466+0300] {subprocess.py:93} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/petr/project/venv/lib/python3.10/site-packages (from Deprecated->PyGithub) (1.15.0)
[2023-11-08T20:06:44.506+0300] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.5 in /home/petr/project/venv/lib/python3.10/site-packages (from python-dateutil->PyGithub) (1.16.0)
[2023-11-08T20:06:44.507+0300] {subprocess.py:93} INFO - Requirement already satisfied: pycparser in /home/petr/project/venv/lib/python3.10/site-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub) (2.21)
[2023-11-08T20:07:01.770+0300] {subprocess.py:93} INFO - Installing collected packages: pynacl, PyGithub
[2023-11-08T20:07:03.383+0300] {subprocess.py:93} INFO - Successfully installed PyGithub-2.1.1 pynacl-1.5.0
[2023-11-08T20:07:08.415+0300] {subprocess.py:93} INFO - /home/petr/project/venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-08T20:07:08.416+0300] {subprocess.py:93} INFO - 
[2023-11-08T20:07:08.416+0300] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-08T20:07:08.416+0300] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-08T20:07:08.566+0300] {subprocess.py:93} INFO - /home/petr/project/venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
[2023-11-08T20:07:08.566+0300] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-08T20:07:08.566+0300] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO - 2023/11/08 20:07:09 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO - The git executable must be specified in one of the following ways:
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO -     - be included in your $PATH
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO -     - explicitly set via git.refresh()
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO - 
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO - All git commands will error until this is rectified.
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO - 
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO - This initial warning can be silenced or aggravated in the future by setting the
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2023-11-08T20:07:09.229+0300] {subprocess.py:93} INFO -     - quiet|q|silence|s|none|n|0: for no warning or exception
[2023-11-08T20:07:09.230+0300] {subprocess.py:93} INFO -     - warn|w|warning|1: for a printed warning
[2023-11-08T20:07:09.252+0300] {subprocess.py:93} INFO -     - error|e|raise|r|2: for a raised exception
[2023-11-08T20:07:09.252+0300] {subprocess.py:93} INFO - 
[2023-11-08T20:07:09.252+0300] {subprocess.py:93} INFO - Example:
[2023-11-08T20:07:09.252+0300] {subprocess.py:93} INFO -     export GIT_PYTHON_REFRESH=quiet
[2023-11-08T20:07:09.252+0300] {subprocess.py:93} INFO - 
[2023-11-08T20:07:13.972+0300] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-08T20:07:14.275+0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_task_score, task_id=get_data, execution_date=20231108T170619, start_date=20231108T170635, end_date=20231108T170714
[2023-11-08T20:07:14.470+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-08T20:07:14.746+0300] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
