[2023-11-08T18:14:48.285+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_task_score.get_data manual__2023-11-08T15:14:39.633051+00:00 [queued]>
[2023-11-08T18:14:48.294+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_task_score.get_data manual__2023-11-08T15:14:39.633051+00:00 [queued]>
[2023-11-08T18:14:48.294+0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-08T18:14:48.343+0300] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-11-08 15:14:39.633051+00:00
[2023-11-08T18:14:48.346+0300] {standard_task_runner.py:57} INFO - Started process 24205 to run task
[2023-11-08T18:14:48.370+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'my_task_score', 'get_data', 'manual__2023-11-08T15:14:39.633051+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/run_airflow.py', '--cfg-path', '/tmp/tmpv14jdas1']
[2023-11-08T18:14:48.370+0300] {standard_task_runner.py:85} INFO - Job 14: Subtask get_data
[2023-11-08T18:14:48.685+0300] {task_command.py:416} INFO - Running <TaskInstance: my_task_score.get_data manual__2023-11-08T15:14:39.633051+00:00 [running]> on host MLOPS-3-3.myguest.virtualbox.org
[2023-11-08T18:14:49.110+0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='my_task_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T15:14:39.633051+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T15:14:39.633051+00:00'
[2023-11-08T18:14:49.111+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T18:14:49.124+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/petr/project/scripts/get_data.py']
[2023-11-08T18:14:49.143+0300] {subprocess.py:86} INFO - Output:
[2023-11-08T18:14:49.185+0300] {subprocess.py:93} INFO -   File "/home/petr/project/scripts/get_data.py", line 4
[2023-11-08T18:14:49.206+0300] {subprocess.py:93} INFO -     !pip install github
[2023-11-08T18:14:49.206+0300] {subprocess.py:93} INFO -     ^
[2023-11-08T18:14:49.206+0300] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2023-11-08T18:14:49.206+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-08T18:14:49.257+0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/petr/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-08T18:14:49.273+0300] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=my_task_score, task_id=get_data, execution_date=20231108T151439, start_date=20231108T151448, end_date=20231108T151449
[2023-11-08T18:14:49.319+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 24205)
[2023-11-08T18:14:49.353+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T18:14:49.395+0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
