[2023-12-02T14:11:36.118+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: compare_task_score.test_model manual__2023-12-02T11:04:53.202332+00:00 [queued]>
[2023-12-02T14:11:36.433+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: compare_task_score.test_model manual__2023-12-02T11:04:53.202332+00:00 [queued]>
[2023-12-02T14:11:36.433+0300] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-02T14:11:36.475+0300] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): test_model> on 2023-12-02 11:04:53.202332+00:00
[2023-12-02T14:11:36.484+0300] {standard_task_runner.py:57} INFO - Started process 16037 to run task
[2023-12-02T14:11:36.494+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'compare_task_score', 'test_model', 'manual__2023-12-02T11:04:53.202332+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/run_airflow.py', '--cfg-path', '/tmp/tmp6mmcq03i']
[2023-12-02T14:11:36.496+0300] {standard_task_runner.py:85} INFO - Job 70: Subtask test_model
[2023-12-02T14:11:36.682+0300] {task_command.py:416} INFO - Running <TaskInstance: compare_task_score.test_model manual__2023-12-02T11:04:53.202332+00:00 [running]> on host MLOPS-3-3.myguest.virtualbox.org
[2023-12-02T14:11:36.890+0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='compare_task_score' AIRFLOW_CTX_TASK_ID='test_model' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T11:04:53.202332+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-02T11:04:53.202332+00:00'
[2023-12-02T14:11:36.892+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-02T14:11:36.893+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/petr/project/scripts/test_model.py']
[2023-12-02T14:11:36.909+0300] {subprocess.py:86} INFO - Output:
[2023-12-02T14:11:39.823+0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-02T14:11:39.839+0300] {subprocess.py:93} INFO -   File "/home/petr/project/scripts/test_model.py", line 16, in <module>
[2023-12-02T14:11:39.840+0300] {subprocess.py:93} INFO -     model_2 = TimeSeriesForestClassifier(n_estimators=100,random_state=47)
[2023-12-02T14:11:39.840+0300] {subprocess.py:93} INFO - NameError: name 'TimeSeriesForestClassifier' is not defined
[2023-12-02T14:11:40.247+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-02T14:11:40.280+0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/petr/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-02T14:11:40.295+0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=compare_task_score, task_id=test_model, execution_date=20231202T110453, start_date=20231202T111136, end_date=20231202T111140
[2023-12-02T14:11:40.325+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 70 for task test_model (Bash command failed. The command returned a non-zero exit code 1.; 16037)
[2023-12-02T14:11:40.349+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-02T14:11:40.392+0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
