[2023-11-08T18:12:17.892+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_task_score.get_data manual__2023-11-08T15:07:06.207177+00:00 [queued]>
[2023-11-08T18:12:17.915+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_task_score.get_data manual__2023-11-08T15:07:06.207177+00:00 [queued]>
[2023-11-08T18:12:17.915+0300] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-08T18:12:17.948+0300] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-11-08 15:07:06.207177+00:00
[2023-11-08T18:12:17.956+0300] {standard_task_runner.py:57} INFO - Started process 23692 to run task
[2023-11-08T18:12:17.968+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'my_task_score', 'get_data', 'manual__2023-11-08T15:07:06.207177+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/run_airflow.py', '--cfg-path', '/tmp/tmpgr0tfo58']
[2023-11-08T18:12:17.969+0300] {standard_task_runner.py:85} INFO - Job 13: Subtask get_data
[2023-11-08T18:12:18.128+0300] {task_command.py:416} INFO - Running <TaskInstance: my_task_score.get_data manual__2023-11-08T15:07:06.207177+00:00 [running]> on host MLOPS-3-3.myguest.virtualbox.org
[2023-11-08T18:12:18.368+0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='my_task_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T15:07:06.207177+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T15:07:06.207177+00:00'
[2023-11-08T18:12:18.370+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T18:12:18.377+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/petr/project/scripts/get_data.py']
[2023-11-08T18:12:18.395+0300] {subprocess.py:86} INFO - Output:
[2023-11-08T18:12:18.444+0300] {subprocess.py:93} INFO -   File "/home/petr/project/scripts/get_data.py", line 4
[2023-11-08T18:12:18.447+0300] {subprocess.py:93} INFO -     !pip install github
[2023-11-08T18:12:18.459+0300] {subprocess.py:93} INFO -     ^
[2023-11-08T18:12:18.459+0300] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2023-11-08T18:12:18.460+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-08T18:12:18.496+0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/petr/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-08T18:12:18.500+0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_task_score, task_id=get_data, execution_date=20231108T150706, start_date=20231108T151217, end_date=20231108T151218
[2023-11-08T18:12:18.531+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 23692)
[2023-11-08T18:12:18.564+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T18:12:18.621+0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
